#version: '3.8'

services:
  symfony-app:
    build: 
      context: .    # Ubicación del Dockerfile
      dockerfile: Dockerfile
    container_name: symfony-spotify
    volumes:
    #- /c/Users/rubee/OneDrive/Escritorio/SymfonyProyectos/MySpotify:/var/www/symfony 
    - /home/alumnotv/ProyectoSpotify/MySpotify:/var/www/symfony
    working_dir: /var/www/symfony
    ports:
      - "8000:8000"
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    command: tail -f /dev/null
    networks:
      - symfony-network
    depends_on:      
      - mysql
  mysql:
    image: mysql:8.0    # Imagen oficial de MySQL
    container_name: mysql_spotify
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: dbmyspotify
    volumes:
      - ./dataMYSQL:/var/lib/mysql
    ports:
      - "3306:3306"
    
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge



